export const GET_BOOKS = 'GET_BOOKS';
export const GET_GAMES = 'GET_GAMES';
export const ADD_NEW_BOOK = 'ADD_NEW_BOOK';
export const ADD_NEW_GAME = 'ADD_NEW_GAME';
export const DELETE_BOOK ='DELETE_BOOK';
export const SET_CURRENT ='SET_CURRENT';
export const CLEAR_CURRENT ='CLEAR_CURRENT';
export const UPDATE_BOOK='UPDATE_BOOK';
export const UPDATE_GAME='UPDATE_GAME';
export const FILTER_BOOKS ='FILTER_BOOK';
export const FILTER_GAMES ='FILTER_GAMES';
export const CLEAR_BOOKS ='CLEAR_BOOK';
export const CLEAR_GAMES ='CLEAR_GAMES';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const BOOK_ERROR = 'BOOK_ERROR'
export const GAME_ERROR = 'GAME_ERROR'
